// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnHXc8r1AwAIt-Y95M81mKSJwIjEFnRkU',
    appId: '1:787533474585:web:65cd190b96a08992de3388',
    messagingSenderId: '787533474585',
    projectId: 'wissenlms',
    authDomain: 'wissenlms.firebaseapp.com',
    databaseURL: 'https://wissenlms.firebaseio.com',
    storageBucket: 'wissenlms.appspot.com',
    measurementId: 'G-GK539S11XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6kB3DO2MSVpMAv_CQXCyzHl-8wyIigCU',
    appId: '1:787533474585:android:48ceeb8dbbd8b4efde3388',
    messagingSenderId: '787533474585',
    projectId: 'wissenlms',
    databaseURL: 'https://wissenlms.firebaseio.com',
    storageBucket: 'wissenlms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHkU0PBp8sj9CE86UAePYZKDzgb46dZsM',
    appId: '1:787533474585:ios:edaf2700fa5e7f51de3388',
    messagingSenderId: '787533474585',
    projectId: 'wissenlms',
    databaseURL: 'https://wissenlms.firebaseio.com',
    storageBucket: 'wissenlms.appspot.com',
    androidClientId: '787533474585-f8s7qqb8t3bjcu2q1144qs6e0a2v95on.apps.googleusercontent.com',
    iosClientId: '787533474585-85navln2u1o0bcbevfhinkhd6q4dsq16.apps.googleusercontent.com',
    iosBundleId: 'com.social.feed.socialFeed',
  );
}
